######## Stellar Theme Configuration ########
######## 参考: https://xaoxuu.com/wiki/stellar/ ########

######## Sidebar ########
# 左上角显示的 logo 区域，包含图标、大标题、副标题
logo:
  avatar: '[{config.avatar}](/about/)'
  title: '[{config.title}](/)'
  subtitle: '{config.subtitle}'

# 侧边栏主功能导航菜单
menubar:
  columns: 4
  items:
    - id: post
      theme: '#1BCDFC'
      icon: solar:documents-bold-duotone
      title: 博客
      url: /
    - id: wiki
      theme: '#3DC550'
      icon: solar:notebook-bookmark-bold-duotone
      title: 归档
      url: /archives/
    - id: explore
      theme: '#FA6400'
      icon: solar:planet-bold-duotone
      title: 探索
      url: /categories/
    - id: about
      theme: '#F44336'
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/942ebbf1a4b91.svg"/>'
      title: 关于
      url: /about/

######## Main ########
# 站点主结构树
site_tree:
  # 主页配置
  home:
    leftbar: welcome, recent, tags
    rightbar: timeline
  # 博客列表页配置
  index_blog:
    base_dir: blog
    menu_id: post
    leftbar: welcome, recent
    rightbar:
  # 文档列表页配置
  index_wiki:
    base_dir: wiki
    menu_id: wiki
    leftbar: related, recent
    rightbar:
  # 博客文章内页配置
  post:
    menu_id: post
    leftbar: related, recent
    rightbar: ghrepo, toc
  # 其它自定义页面配置 layout: page
  page:
    leftbar: recent
    rightbar: toc

######## Article ########
article:
  type: tech
  cover_ratio: 2
  banner_ratio: 2.5
  auto_excerpt: 128
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  share: [wechat, weibo, link]

######## Search ########
search:
  service: local_search
  local_search:
    field: all
    path: /search.json
    content: true

######## Comments ########
comments:
  service: giscus
  comment_title: 快来参与讨论吧~
  lazyload: false
  giscus:
    src: https://giscus.app/client.js
    data-repo: fairyeye/fairyeye.github.io
    data-repo-id: MDEwOlJlcG9zaXRvcnkyNTM2NzI0OTU=
    data-category: Announcements
    data-category-id: DIC_kwDODx68L84C1FEi
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    crossorigin: anonymous

######## Footer ########
footer:
  social:
    github:
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/08a41b181ce68.svg"/>'
      url: https://github.com/fairyeye
    email:
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/3845874.svg"/>'
      url: mailto:your-email@example.com
  sitemap:
    - title: 博客
      items:
        - '[近期发布](/)'
        - '[分类](/categories/)'
        - '[标签](/tags/)'
        - '[归档](/归档/)'
    - title: 关于
      items:
        - '[关于我](/about/)'
        - '[GitHub](https://github.com/fairyeye)'
        - '[RSS](/atom.xml)'
  content: |
    本站由 [{config.author}]({config.url}) 使用 [Hexo](https://hexo.io/) 和 [Stellar](https://xaoxuu.com/wiki/stellar/) 主题创建。
    本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。

######## Tag Plugins ########
tag_plugins:
  note:
    default_color: 'light'
    border: true
  checkbox:
    interactive: false
  quot:
    default:
      prefix: bxs:quote-left
      suffix: bxs:quote-right
    hashtag:
      prefix: solar:hashtag-square-bold
    question:
      prefix: ph:seal-question-fill
  emoji:
    default: https://gcore.jsdelivr.net/gh/cdn-x/emoticons@3.1/qq/{name}.gif
    twemoji: https://gcore.jsdelivr.net/gh/twitter/twemoji/assets/svg/{name}.svg
    qq: https://gcore.jsdelivr.net/gh/cdn-x/emoticons@3.1/qq/{name}.gif
